[package]
name = "frqgen-cli"
description = "KiraFrqGen command-line interface"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "kirafrqgen-cli"
path = "src/main.rs"

[dependencies]
frqgen.workspace = true
clap.workspace = true
ctrlc.workspace = true

[dev-dependencies]
hound.workspace = true
frq-core.workspace = true
