//! The credits and third-party license notices shared by the CLI and the GUI.
//!
//! `CREDITS.md` at the repository root is the single source of truth: its prose
//! is hand-written, and the `credits:deps-*` marker blocks are generated by
//! `cargo xtask credits`.

use std::sync::OnceLock;

mod render;

pub use render::{Style, render};

const CREDITS_MD: &str = include_str!("../../../CREDITS.md");

// HTML comments that delimit the generated blocks in `CREDITS.md`. The writer
// in `xtask` goes through [`assemble`], so both sides share this one copy.
const SUMMARY_BEGIN: &str = "<!-- credits:deps-summary:begin -->";
const SUMMARY_END: &str = "<!-- credits:deps-summary:end -->";
const FULL_BEGIN: &str = "<!-- credits:deps-full:begin -->";
const FULL_END: &str = "<!-- credits:deps-full:end -->";

/// The complete credits: prose, the dependency index and every license text.
pub fn full() -> &'static str {
    static FULL: OnceLock<String> = OnceLock::new();
    FULL.get_or_init(|| strip_markers(CREDITS_MD)).as_str()
}

/// The credits without the full license texts: prose and the dependency index.
pub fn summary() -> &'static str {
    static SUMMARY: OnceLock<String> = OnceLock::new();
    SUMMARY
        .get_or_init(|| strip_markers(&drop_block(CREDITS_MD, FULL_BEGIN, FULL_END)))
        .as_str()
}

/// The credits a surface should show: `license_texts` picks the full variant,
/// otherwise the compact one.
pub fn for_display(license_texts: bool) -> &'static str {
    if license_texts { full() } else { summary() }
}

/// Replace the generated dependency-index and license-text blocks in `doc`.
/// This is how `cargo xtask credits` rewrites `CREDITS.md`.
///
/// The document's line endings are preserved, so a CRLF checkout does not look
/// stale to `cargo xtask credits --check` after every run.
pub fn assemble(doc: &str, summary: &str, full: &str) -> Result<String, String> {
    let crlf = doc.contains("\r\n");
    let doc = doc.replace("\r\n", "\n");
    let summary = summary.replace("\r\n", "\n");
    let full = full.replace("\r\n", "\n");
    let out = splice_block(&doc, SUMMARY_BEGIN, SUMMARY_END, &summary)?;
    let out = splice_block(&out, FULL_BEGIN, FULL_END, &full)?;
    Ok(if crlf { out.replace('\n', "\r\n") } else { out })
}

/// Drop the `begin`..=`end` block, its markers included.
fn drop_block(doc: &str, begin: &str, end: &str) -> String {
    let mut out = String::new();
    let mut inside = false;
    for line in doc.lines() {
        if line.trim() == begin {
            inside = true;
        } else if line.trim() == end {
            inside = false;
        } else if !inside {
            out.push_str(line);
            out.push('\n');
        }
    }
    out
}

/// Replace whatever sits between the `begin` and `end` marker lines with
/// `body`, keeping the markers.
fn splice_block(doc: &str, begin: &str, end: &str, body: &str) -> Result<String, String> {
    enum State {
        Outside,
        Inside,
    }

    let mut out = String::new();
    let mut state = State::Outside;
    let mut found_begin = false;
    let mut found_end = false;
    for line in doc.lines() {
        match state {
            State::Outside if line.trim() == begin => {
                found_begin = true;
                out.push_str(line);
                out.push('\n');
                out.push('\n');
                out.push_str(body.trim_end());
                out.push('\n');
                state = State::Inside;
            }
            State::Inside if line.trim() == end => {
                found_end = true;
                out.push('\n');
                out.push_str(line);
                out.push('\n');
                state = State::Outside;
            }
            State::Inside => {}
            State::Outside => {
                out.push_str(line);
                out.push('\n');
            }
        }
    }
    if !found_begin || !found_end {
        return Err(format!("CREDITS.md is missing the {begin} / {end} markers"));
    }
    Ok(out)
}

/// Remove the marker lines, which are HTML comments only the generator uses;
/// plain-text surfaces should not show them.
fn strip_markers(doc: &str) -> String {
    let mut out = String::new();
    for line in doc.lines() {
        if !is_marker(line) {
            out.push_str(line);
            out.push('\n');
        }
    }
    out
}

fn is_marker(line: &str) -> bool {
    let line = line.trim();
    [SUMMARY_BEGIN, SUMMARY_END, FULL_BEGIN, FULL_END].contains(&line)
}

#[cfg(test)]
mod tests {
    use super::*;

    const FIXTURE: &str = "\
# Credits

prose

<!-- credits:deps-summary:begin -->
- `dep` 1.0.0 - MIT
<!-- credits:deps-summary:end -->

<!-- credits:deps-full:begin -->
### Full license texts

BIG LICENSE BODY
<!-- credits:deps-full:end -->
";

    #[test]
    fn summary_keeps_the_prose_and_index_but_drops_the_license_texts() {
        let text = strip_markers(&drop_block(FIXTURE, FULL_BEGIN, FULL_END));
        assert!(text.contains("prose"));
        assert!(text.contains("`dep` 1.0.0 - MIT"));
        assert!(!text.contains("BIG LICENSE BODY"));
        assert!(!text.contains("credits:deps"), "{text}");
    }

    #[test]
    fn full_keeps_everything_but_the_markers() {
        let text = strip_markers(FIXTURE);
        assert!(text.contains("prose"));
        assert!(text.contains("`dep` 1.0.0 - MIT"));
        assert!(text.contains("BIG LICENSE BODY"));
        assert!(!text.contains("credits:deps"), "{text}");
    }

    #[test]
    fn assemble_replaces_both_blocks_between_their_markers() {
        let out = assemble(FIXTURE, "- NEW INDEX", "NEW TEXTS").unwrap();
        assert!(out.contains("- NEW INDEX"));
        assert!(out.contains("NEW TEXTS"));
        assert!(!out.contains("`dep` 1.0.0 - MIT"));
        assert!(!out.contains("BIG LICENSE BODY"));
        assert_eq!(
            out,
            assemble(FIXTURE, "- NEW INDEX", "NEW TEXTS").unwrap(),
            "assembling is idempotent"
        );
    }

    #[test]
    fn assemble_rejects_a_document_without_the_markers() {
        assert!(assemble("# no markers\n", "x", "y").is_err());
    }

    #[test]
    fn assemble_preserves_crlf_line_endings() {
        let doc = FIXTURE.replace('\n', "\r\n");
        let out = assemble(&doc, "- INDEX", "TEXTS").unwrap();
        assert!(out.contains("- INDEX"));
        assert!(out.contains("TEXTS"));
        assert!(
            !out.replace("\r\n", "").contains('\n'),
            "a CRLF document must stay CRLF"
        );
    }
}
