//! The credits and third-party license notices shared by the CLI and the GUI.
//!
//! `CREDITS.md` at the repository root is the single source of truth. Its prose
//! is hand-written; everything between the `credits:deps-*` markers is
//! generated by `cargo xtask credits`. Both binaries render this one document,
//! so there is nothing else to keep in sync.

use std::sync::OnceLock;

const CREDITS_MD: &str = include_str!("../../../CREDITS.md");

/// Start of the generated dependency index block in `CREDITS.md`.
pub const SUMMARY_BEGIN: &str = "<!-- credits:deps-summary:begin -->";
/// End of the generated dependency index block in `CREDITS.md`.
pub const SUMMARY_END: &str = "<!-- credits:deps-summary:end -->";
/// Start of the generated full-license-text block in `CREDITS.md`.
pub const FULL_BEGIN: &str = "<!-- credits:deps-full:begin -->";
/// End of the generated full-license-text block in `CREDITS.md`.
pub const FULL_END: &str = "<!-- credits:deps-full:end -->";

/// The complete credits: prose, the dependency index and every license text.
pub fn full() -> &'static str {
    static FULL: OnceLock<String> = OnceLock::new();
    FULL.get_or_init(|| strip_markers(CREDITS_MD)).as_str()
}

/// The credits without the full license texts: prose and the dependency index,
/// for the `--license` default that should stay readable in a terminal.
pub fn summary() -> &'static str {
    static SUMMARY: OnceLock<String> = OnceLock::new();
    SUMMARY
        .get_or_init(|| strip_markers(&drop_block(CREDITS_MD, FULL_BEGIN, FULL_END)))
        .as_str()
}

/// Drop the `begin`..=`end` block, its markers included.
fn drop_block(doc: &str, begin: &str, end: &str) -> String {
    let mut out = String::new();
    let mut inside = false;
    for line in doc.lines() {
        if line.trim() == begin {
            inside = true;
        } else if line.trim() == end {
            inside = false;
        } else if !inside {
            out.push_str(line);
            out.push('\n');
        }
    }
    out
}

/// Remove the marker lines, which are HTML comments only the generator uses;
/// plain-text surfaces should not show them.
fn strip_markers(doc: &str) -> String {
    let mut out = String::new();
    for line in doc.lines() {
        if !is_marker(line) {
            out.push_str(line);
            out.push('\n');
        }
    }
    out
}

fn is_marker(line: &str) -> bool {
    let line = line.trim();
    [SUMMARY_BEGIN, SUMMARY_END, FULL_BEGIN, FULL_END].contains(&line)
}

#[cfg(test)]
mod tests {
    use super::*;

    const FIXTURE: &str = "\
# Credits

prose

<!-- credits:deps-summary:begin -->
- `dep` 1.0.0 - MIT
<!-- credits:deps-summary:end -->

<!-- credits:deps-full:begin -->
### Full license texts

BIG LICENSE BODY
<!-- credits:deps-full:end -->
";

    #[test]
    fn summary_keeps_the_prose_and_index_but_drops_the_license_texts() {
        let text = strip_markers(&drop_block(FIXTURE, FULL_BEGIN, FULL_END));
        assert!(text.contains("prose"));
        assert!(text.contains("`dep` 1.0.0 - MIT"));
        assert!(!text.contains("BIG LICENSE BODY"));
        assert!(!text.contains("credits:deps"), "{text}");
    }

    #[test]
    fn full_keeps_everything_but_the_markers() {
        let text = strip_markers(FIXTURE);
        assert!(text.contains("prose"));
        assert!(text.contains("`dep` 1.0.0 - MIT"));
        assert!(text.contains("BIG LICENSE BODY"));
        assert!(!text.contains("credits:deps"), "{text}");
    }
}
