[package]
name = "kira-frq-world"
description = "Safe Rust wrapper over vendored WORLD (DIO / Harvest / StoneMask)"
license = "BSD-3-Clause"
version.workspace = true
edition.workspace = true
publish.workspace = true

[build-dependencies]
cc.workspace = true

[dev-dependencies]
hound.workspace = true
