[package]
name = "kira-frqgen-gui"
description = "KiraFrqGen egui interface"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "KiraFrqGen"
path = "src/main.rs"

[dependencies]
kira-frqgen.workspace = true
eframe.workspace = true
rfd.workspace = true
egui-phosphor.workspace = true
